Specific params
pndaproject/pnda-heat-templates pull request #88
Opened 2017-04-27 16:03 UTC by klyr

Do not merge the PR right now, I need some feedback and discussions first

2017-04-27 16:11 UTC, klyr commented
The idea of this is to add a single `specific_config` parameter in pnda_env.yaml like the following:

    specific_config: '[kafka_vlan]="2006" [kafka_iface]="vlan2006" [gizmo]=42'

Then, in scripts files, we can use

    if [ ${conf[gizmo]} -gt 42 ]; ...

It will also update the `env_parameters.sls` pillar file:

    specific_config:
      kafka_vlan: 2006
      kafka_iface: vlan2006
      gizmo: 42

That we will be able to use in salt sls files like this:

    pillar['specific_config']['gizmo']

By  doing that, we can add very specific parameters without having to edit the templates.

2017-04-28 08:09 UTC, jgarnier commented
I think this is good @klyr , this will enable us more flexibility and can reduce our current implementation to something more generic !

2017-04-28 09:18 UTC, jeclarke approved these changes

2017-04-28 09:39 UTC, jeclarke requested changes
Could you quash the commits and update the changelog?

2017-04-28 11:39 UTC, jeclarke approved these changes

2017-04-28 11:40 UTC, merged